review
Pol-Gallardo/perpetuals-guardians pull request #4
Opened 2023-09-24 18:05 UTC by Pol-Gallardo

2023-09-24 18:09 UTC, 0xdimo requested changes

2023-09-24 18:09 UTC, 0xdimo commented on src/PerpetualGuardian.sol
> +    AggregatorV3Interface private s_priceFeed;
What do you think about calling it `ethDaiPriceFeed`

2023-09-24 18:09 UTC, 0xdimo commented on src/PerpetualGuardian.sol
> +    function getPositionCollateral(uint256 positionIndex) public view returns (uint256) {
Why do we need this :?

2023-09-24 18:09 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
Please uncomment the tests. We need to have them. Also add tests for the price feed

2023-09-24 18:14 UTC, Pol-Gallardo commented on script/DeployPerpetualGuardian.s.sol
> -            dai,
OKey It's fine I like it Dai

2023-09-24 18:14 UTC, Pol-Gallardo commented on src/PerpetualGuardian.sol
> +    AggregatorV3Interface private s_priceFeed;
yes better It's more information about this

2023-09-24 18:16 UTC, Pol-Gallardo commented on src/PerpetualGuardian.sol
> +    function getPositionCollateral(uint256 positionIndex) public view returns (uint256) {
This function is to work the increasePositionSize

2023-09-24 18:17 UTC, Pol-Gallardo commented on test/unit/PerpetualGuardian.t.sol
I commented out the tests to be able to do a 'forge build.' I'll rewrite them to make them work but using the price feed and fetching real prices.

2023-09-24 18:19 UTC, 0xdimo commented on src/PerpetualGuardian.sol
> +    function getPositionCollateral(uint256 positionIndex) public view returns (uint256) {
You can get the collateral from the mapping

2023-09-24 18:20 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
Great, waiting for this 💯

2023-09-24 18:24 UTC, Pol-Gallardo commented on src/PerpetualGuardian.sol
> +    function getPositionCollateral(uint256 positionIndex) public view returns (uint256) {
Did you see how I modified the logic in 'openPosition' and 'increasePositionSize'?

2023-09-25 13:20 UTC, 0xdimo requested changes

2023-09-25 13:20 UTC, 0xdimo commented on src/PerpetualGuardian.sol
> +        }
Why do we check the size :?

2023-09-25 13:20 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
> +    modifier addLP() {
I love this one!

2023-09-25 13:20 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
> +    function testGetTokenAmountFromUsd() public {
nice!

2023-09-25 13:20 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
> +    function setUp() external {
why external :?

2023-09-25 13:21 UTC, 0xdimo commented on lib/solmate
I don't think we need solmate :?

2023-09-25 13:45 UTC, 0xdimo commented on script/HelperConfig.s.sol
> +            ethUsdPriceFeed: 0x694AA1769357215DE4FAC081bf1f309aDC325306,
don't we need eth/DAI pricefeed?

2023-09-25 13:46 UTC, 0xdimo commented on src/PerpetualGuardian.sol
> +    error PerpetualGuardian__SizeExceeds();
let's delete this one if we don't use it

2023-09-25 13:47 UTC, 0xdimo commented on test/unit/PerpetualGuardian.t.sol
> +        int256 ethUsdUpdatedPrice = 500e8;
dai instead of USD

2023-09-25 14:04 UTC, merged